# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
#    scan
    scan(
      scheme: "PreSniffObjcDemo",
      clean: true,
      code_coverage: true,
      device: "iPhone 5s (9.3)",
    )
  end

  desc "Runs code coverage analysis"
  lane :codecov do
    scan(
      scheme: "PreSniffSDKDemo",
      clean: true,
      code_coverage: true,
      device: "iPhone 5s (9.3)",
    )
    slather(
      cobertura_xml: true,
      output_directory: "coverage_output",
      proj: "PreSniffSDK/PreSniffSDK.xcodeproj",
      scheme: "PreSniffSDK"
    #  ignore:['../../*']
    )
    sh "echo codecov token: " + ENV["CODECOV_TOKEN"]
    sh "cd .. && curl -s https://codecov.io/bash | bash -s -f ./coverage_output/cobertura.xml -J 'PreSniffSDK'"
    sh "cd .. && slather coverage --html --scheme PreSniffSDK  PreSniffSDK/PreSniffSDK.xcodeproj"
    sh "cd .. && fastlane/qshell account "+ ENV["QINIU_AK"] + " " + ENV["QINIU_SK"]
    sh "cd .. && fastlane/qshell qupload fastlane/qiniu_upload.conf"
    sh "cd .. && sed -i.bak 's/\"\",/\""+ENV["TRAVIS_COMMIT"]+"\\\/"+"\",/g' fastlane/qiniu_upload.conf && fastlane/qshell qupload fastlane/qiniu_upload.conf"
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    scan(
      scheme: "PreSniffObjcDemo",
      clean: true,
      code_coverage: true
    )
    gym(
      export_method:"enterprise",
      workspace:"PreSniffObjcDemo/PreSniffObjcDemo.xcworkspace",
      scheme: "PreSniffObjcDemo"
      ) # Build your app - more options available

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "PreSniffSDKDemo") # Build your app - more options available
    deliver(force: true)
    # frameit
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
