# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

desc "Runs all the tests"
lane :test do
  scan(
    scheme: "PreSniffObjcDemo",
    clean: true,
    code_coverage: true
  )
end

desc "Submit a new Beta Build to fir.im"
lane :beta do
  scan
  path = gym(
    export_method:"enterprise",
    workspace:"PreSniffObjcDemo/PreSniffObjcDemo.xcworkspace",
    scheme: "PreSniffObjcDemo"
    ) # Build your app - more options available
  sh "bundle exec fir publish #{path} -T " + ENV["FIR_TOKEN"]
end

desc "Deploy a new version to the App Store"
lane :release do
  # match(type: "appstore")
  # snapshot
  gym(scheme: "PreSniffSDKDemo") # Build your app - more options available
  deliver(force: true)
  # frameit
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
