platform :ios, '8.0'
use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

target 'PreDemObjcDemo' do
    pod 'PreDemCocoa', :path => '../'
end

target 'PreDemSwiftDemo' do
    pod 'PreDemCocoa/Swift', :path => '../'
end

target 'PreDemCocoaTests' do
    pod 'PreDemCocoa', :path => '../'
end

